name = "KLT"
uuid = "08242366-3e31-4689-85e3-00e2dd4e8612"
authors = ["Michael Cassidy"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
